### ISSUE TITLE
Call to action - How to inform users where their action is needed.

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget-ui#105]
Stems form confusion about navigating between groups and rounds. Users need something that guides their actions.

What is a low-cost way we could test doing this? Some thoughts -

* A dashboard
* A modal telling the user where their allocations are when they log in and have unviewed allocations

What do you think @jonlemmon @ahdinosaur ?

**Comment by ahdinosaur** [comment]
stale, we'll re-introduce this in the top-level repo as we process the feedback from our friendly alpha users.
