### ISSUE TITLE
handle unexpected errors

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/cobudget-ui#167]
right now a lot of errors are silently ignored, this is bad.

from https://github.com/open-app/cobudget/issues/54,
> If an error is unhandleable: pop up a modal

**Comment by derekrazo** [comment]
Idk about popping up a modal for unhandled errors... What errors are you referring too?

**Comment by jonlemmon** [comment]
@derekrazo I'm pretty sure it's standard practice. Like on facebook if you try to do something and the whole server falls down and fails, you get a pop-up modal to let you know. Do you have a better idea of how to handle this sort of thing?

**Comment by ahdinosaur** [comment]
meanwhile on gmail, 
![9](https://cloud.githubusercontent.com/assets/719605/6009752/95f1c3f0-ab91-11e4-942d-f061916e6008.png)

**Comment by jonlemmon** [comment]
Hehehe
