### ISSUE TITLE
Oh Noes! Staging broken - Firefox

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget-ui#177]
In Firefox -

The login modal appears but I cannot log in with correct credentials.

Error: 

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create index.js:19

"restful-store " "errorHandler" " +1s" Object { data: Object, status: 401, headers: un/<(), config: Object, statusText: "Unauthorized " } index.js:19

Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]

**Comment by ahdinosaur** [comment]
staging.cobudget.co now uses a new separate staging API, so your existing login deets aren't expected to work.
