### ISSUE TITLE
Oh Noes! Staging broken - Chrome - 403 

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget-ui#178]
In Chrome the Login modal never appears -

Error:

https://staging-cobudget-api.herokuapp.com/groups?member_id=26 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by ahdinosaur** [comment]
staging.cobudget.co now uses a new separate staging API, so you need to reset your cookie :stuck_out_tongue:
