### ISSUE TITLE
contribution input doesn't work on some versions of Firefox

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/cobudget-ui#180]
unfortunately i can't reproduce with my browser, so i'll need to find a friend (@s01us) to lend a browser.

**Comment by getresults** [comment]
@ahdinosaur - if you want access to our team BrowserStack.com account for testing on different platforms / browsers drop me a line.

**Comment by derekrazo** [comment]
@ahdinosaur how can I help make this easier to debug? do you need my comp
for some time? This is an important one to solve I reckon!
ᐧ

**Comment by ahdinosaur** [comment]
hmm, i upgraded my Iceweasel (Firefox without the branding) from 31esr to 35.0.1, but still can't reproduce the issue. what versions have we confirmed don't work?

@getresults that'd be real sweet, cheers.

@derekrazo being able to borrow your computer would be awesome, thanks.

:penguin:
